hike_slovakia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('hikes/', include('hikes.urls')),
    path('', include('home.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hikes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_hikes, name='hikes'),
    path('<hike_id>', views.hike_detail, name='hike_detail'),
    path('add_hike/', views.add_hike, name='add_hike'),
    path('edit_hike/<hike_id>/', views.edit_hike, name='edit_hike'),
    path('delete_hike/<hike_id>/', views.delete_hike, name='delete_hike'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home')
]

hikes/models.py
from django.db import models


class Hike(models.Model):
    """ Model to store hike details """
    EASY = 0
    MODERATE = 1
    DIFFICULT = 2
    DIFFICULTY_CHOICES = [
        (EASY, 'Easy'),
        (MODERATE, 'Moderate'),
        (DIFFICULT, 'Difficult'),
    ]
    difficulty = models.IntegerField(
        choices=DIFFICULTY_CHOICES,
        default=EASY,
    )
    title = models.CharField(max_length=60, blank=False, null=False)
    description = models.TextField(max_length=500, blank=False, null=False)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='hikes', null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)

    def __str__(self):
        return str(self.title)


class ScheduledHike(models.Model):
    """ Model to assign scheduled dates to hikes """
    hike = models.ForeignKey('Hike', on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return f'Hike {self.hike} is scheduled for {self.date}'

    class Meta:
        """ Only one combination of hike/date allowed """
        constraints = [
            models.UniqueConstraint(
                fields=['hike', 'date'],
                name='unique_hike'),
        ]

hikes/forms.py
from django import forms
from .models import Hike


class HikeForm (forms.ModelForm):
    """ Form to create and edit hikes """
    class Meta:
        model = Hike
        fields = ['difficulty', 'title', 'description', 'price', 'image']

        labels = {
            'title': 'Hike Name',
            'difficulty': 'Difficulty',
            'description': 'Description',
            'price': 'Price',
            'image': 'Image  (use image in landscape orientation - 1920x1280)',
        }

hikes/views.py
from datetime import datetime
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Hike, ScheduledHike
from .forms import HikeForm


def all_hikes(request):
    """ A view to show all hikes """

    hikes = Hike.objects.all()

    context = {
        'hikes': hikes,
    }

    return render(request, 'hikes/hikes.html', context)


def hike_detail(request, hike_id):
    """
    A view to show individual hike details.
    Filters only scheduled hikes that are in the future.
    """

    hike = get_object_or_404(Hike, pk=hike_id)

    today = datetime.today()
    scheduled_hikes = ScheduledHike.objects.filter(
        hike=hike, date__gte=today).order_by('date')

    context = {
        'hike': hike,
        'scheduled_hikes': scheduled_hikes,
    }

    return render(request, 'hikes/hike_detail.html', context)


@login_required
def add_hike(request):
    """ A view to add a new hike """

    if request.user.is_superuser:
        if request.method == 'POST':
            form = HikeForm(request.POST, request.FILES)
            if form.is_valid():
                hike = form.save()
                messages.success(request, 'Successfully added hike!')
                return redirect(reverse('hike_detail', args=[hike.id]))
            else:
                messages.error(request,
                               ('Failed to add hike. '
                                'Please ensure the form is valid.'))
        else:
            form = HikeForm()

        template = 'hikes/add_hike.html'
        context = {
            'form': form,
        }

        return render(request, template, context)
    return render(request, 'home/index.html')


@login_required
def edit_hike(request, hike_id):
    """ A view to edit a hike """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only admins can do that.')
        return redirect(reverse('home'))

    hike = get_object_or_404(Hike, pk=hike_id)
    if request.method == 'POST':
        form = HikeForm(request.POST, request.FILES, instance=hike)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated hike!')
            return redirect(reverse('hike_detail', args=[hike.id]))
        else:
            messages.error(request,
                           ('Failed to update hike. '
                            'Please ensure the form is valid.'))
    else:
        form = HikeForm(instance=hike)
        messages.info(request, f'You are editing {hike.title}')

    template = 'hikes/edit_hike.html'
    context = {
        'form': form,
        'hike': hike,
    }

    return render(request, template, context)


@login_required
def delete_hike(request, hike_id):
    """ A view to delete a hike """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only admins can do that.')
        return redirect(reverse('home'))

    hike = get_object_or_404(Hike, pk=hike_id)
    hike.delete()
    messages.success(request, 'Hike deleted!')
    return redirect(reverse('hikes'))

hikes/templates/hikes/add_hike.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="logo-font mb-4">Hike Management</h2>
            <h5 class="text-muted">Add a Hike</h5>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'add_hike' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="text-right">
                    <a class="btn btn-lg rounded-1 text-uppercase mt-2 py-2 my-1 secondary-btn" href="{% url 'hikes' %}">Cancel</a>
                    <button class="btn btn-lg rounded-1 text-uppercase mt-2 py-2 my-1 regular-btn" type="submit">Add Hike</button>
                </div>
            </form>
        </div>            
    </div>
</div>
{% endblock %}

hikes/templates/hikes/edit_hike.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="mb-4">Hike Management</h2>
            <h5 class="text-muted">Edit a Hike</h5>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'edit_hike' hike.id %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="text-right">
                    <a class="btn btn-lg rounded-1 text-uppercase mt-2 py-2 my-1 secondary-btn" href="{% url 'hike_detail' hike.id %}">Cancel</a>
                    <button class="btn btn-lg rounded-1 text-uppercase mt-2 py-2 my-1 regular-btn" type="submit">Edit Hike</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

hikes/templates/hikes/hike_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="overlay"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-lg-8">
            <div class="image-container my-2">
                {% if hike.image %}
                    <img class="card-img-top img-fluid" src="{{ hike.image.url }}" alt="{{ hike.title }}">
                {% else %}
                    <img class="card-img-top img-fluid" src="{% static '/images/default_image.jpg' %}" alt="{{ hike.title }}">
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-lg-4">
            <div class="hike-details-container mb-5 mt-1 mt-lg-5">
                <h4 class="mb-1 font-weight-bold">{{ hike.title }}</h4>
                <p class="lead text-uppercase mb-0 text-left">{{ hike.get_difficulty_display }}</p>
                <p class="lead mb-0 text-left font-weight-bold">€ {{ hike.price }}</p>
                {% if request.user.is_superuser %}
                <a href="{% url 'edit_hike' hike.id %}" class="btn rounded-1 mt-2 py-2 secondary-btn"
                    aria-label="Edit Hike">EDIT <span><i class="fa-regular fa-pen-to-square"></i></span></a>
                <!-- Trigger/Open The Modal -->
                <button id="myBtn" class="btn rounded-1 mt-2 py-2 regular-btn">DELETE <span><i
                            class="fa-solid fa-trash"></i></span></button>
                {% endif %}
                <p class="mt-3 mb-4">{{ hike.description }}</p>

                <form action="{% url 'view_basket' hike.id %}" method="POST" id="book-hike-form">
                    {% csrf_token %}
                    <div class="form-group w-50">
                        <label for="hike-date-dropdown" id="hike-date-dropdown-label"><strong>Available dates:</strong></label>
                        <select class="form-control rounded-1" name="hike_date_id" id="hike-date-dropdown" required>
                            <option value="" disabled selected>Choose a date ...</option>
                            {% for scheduled_hike in scheduled_hikes %}
                                <option value="{{ scheduled_hike.id }}">{{ scheduled_hike.date }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    {% if user.is_authenticated %}
                        <div class="form-group w-50">
                            <label for="num-people-input" id="num-people-input-label"><strong>Number of hikers (max 5):</strong></label>
                            <input class="form-control" type="number" name="number_of_people" id="num-people-input" value="1" min="1"
                                max="5" required />
                        </div>
                        <button type="submit" id="book-hike-button"
                            class="btn rounded-1 mt-2 py-2 {% if scheduled_hikes|length == 0 %} regular-dis {% else %} regular-btn {% endif %}"
                            {% if scheduled_hikes|length == 0 %} disabled {% endif %}>BOOK HIKE FOR 1 PERSON</button>
                    {% else %}
                        <p>
                            <a class="text-info" href="{% url 'account_signup' %}">Create an account</a> or 
                            <a class="text-info" href="{% url 'account_login' %}">log in</a> to book this hike.
                        </p>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>

<!-- The Modal -->
<div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
    <p>Are you sure you want to delete this hike??</p>
    <a href="{% url 'delete_hike' hike.id %}" class="btn btn-danger" aria-label="Delete Hike">DELETE</a>
  </div>

</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        const numPeopleInput = document.getElementById("num-people-input");
        const bookHikeButton = document.getElementById("book-hike-button");

        numPeopleInput.addEventListener("input", () => {
            // Ensures that the number of people input is always clean and never empty
            numPeopleInput.value = numPeopleInput.value.trim() || "1";

            let correctPersonWord;
            if (numPeopleInput.value == "1") {
                correctPersonWord = "PERSON";
            } else {
                correctPersonWord = "PEOPLE";
            }

            bookHikeButton.innerText = `BOOK HIKE FOR ${numPeopleInput.value} ${correctPersonWord}`;
        });
    </script>
    <script>
        // Get the modal
        let modal = document.getElementById("myModal");

        // Get the button that opens the modal
        let btn = document.getElementById("myBtn");

        // Get the <span> element that closes the modal
        let span = document.getElementsByClassName("close")[0];

        // When the user clicks on the button, open the modal
        btn.onclick = function() {
        modal.style.display = "block";
        };

        // When the user clicks on <span> (x), close the modal
        span.onclick = function() {
        modal.style.display = "none";
        };

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
        };
    </script>
{% endblock %}

hikes/templates/hikes/hikes.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col text-center mt-3">
                <h2>Guided Hikes</h2>
                <hr class="w-50 mb-2 mb-md-5">
            </div>
        </div>
        <div class="row">
            <div class="col-10 offset-1">
                <div class="row">
                    {% for hike in hikes %}
                        <div class="col-sm-6 col-md-6 col-lg-4 mb-3">
                            <div class="card h-100 border rounded shadow">
                                {% if hike.image %}
                                <a href="{% url 'hike_detail' hike.id %}">
                                    <img class="card-img-top img-fluid" src="{{ hike.image.url }}" alt="{{ hike.title }}">
                                </a>
                                {% else %}
                                <a href="{% url 'hike_detail' hike.id %}">
                                    <img class="card-img-top img-fluid" src="{% static '/images/default_image.jpg' %}" alt="{{ hike.title }}">
                                </a>
                                {% endif %}
                                <div class="card-body pb-0">
                                    <h4 class="mb-0 font-weight-bold">{{ hike.title }}</h4>
                                </div>
                                <div class="card-footer bg-white pt-0 pb-3 border-0 text-left">
                                    <div class="row">
                                        <div class="col">
                                            <p class="lead text-uppercase mb-0 text-left">{{ hike.get_difficulty_display }}</p>
                                            <p class="mb-0 text-left font-weight-bold">€ {{ hike.price }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}